name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [released]

jobs:
  call-build:
    uses: "KyoriPowered/.github/.github/workflows/shared-ci.yaml@trunk"
    with:
      publish_releases: true
      publish_release_javadoc: true
    secrets: "inherit"
