name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [released]

permissions:
  actions: "write"
  contents: "write"
  id-token: "write"

jobs:
  call-build:
    uses: "KyoriPowered/ci-cookbook/.github/workflows/java-ci.yaml@2025.10.17"
    with:
      publish_releases: true
      publish_release_javadoc: true
      runtime_version: 17
    secrets:
      DEPLOYMENT_APP_ID: "${{ secrets.DEPLOYMENT_APP_ID }}"
      DEPLOYMENT_APP_SECRET: "${{ secrets.DEPLOYMENT_APP_SECRET }}"
      publishing_env_vars: |
          ORG_GRADLE_PROJECT_sonatypeUsername="${{ secrets.ADVENTURE_SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword="${{ secrets.ADVENTURE_SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_kyoriSigningKey="${{ secrets.ADVENTURE_GPG_KEY }}"
          ORG_GRADLE_PROJECT_kyoriSigningPassword="${{ secrets.ADVENTURE_GPG_PASSWORD }}"

